// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBKV1hv6O6U8Kbn0VGVCqZdtGPUVZeBiWk',
    appId: '1:1083979641425:web:d1809a2c03a02c920cfe70',
    messagingSenderId: '1083979641425',
    projectId: 'bet-drasha',
    authDomain: 'bet-drasha.firebaseapp.com',
    storageBucket: 'bet-drasha.appspot.com',
    measurementId: 'G-CB7CE4CCW4',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBXGzRv3zoUMuCo7Rppf-S9iuEQ3GrZu3g',
    appId: '1:1083979641425:android:2734b8d52a29c5500cfe70',
    messagingSenderId: '1083979641425',
    projectId: 'bet-drasha',
    storageBucket: 'bet-drasha.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCjk94Ws-Wd0aEXh2LWaifA2A5yxla1Sws',
    appId: '1:1083979641425:ios:450764ef25d482740cfe70',
    messagingSenderId: '1083979641425',
    projectId: 'bet-drasha',
    storageBucket: 'bet-drasha.appspot.com',
    iosClientId: '1083979641425-kaiegm2nqt6duasu3uafjq4c5jaah9ec.apps.googleusercontent.com',
    iosBundleId: 'com.example.betDrasha',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCjk94Ws-Wd0aEXh2LWaifA2A5yxla1Sws',
    appId: '1:1083979641425:ios:1005f6eff0cd65970cfe70',
    messagingSenderId: '1083979641425',
    projectId: 'bet-drasha',
    storageBucket: 'bet-drasha.appspot.com',
    iosClientId: '1083979641425-6k5jqspinlkeahcodslqsjg3e3fd91r3.apps.googleusercontent.com',
    iosBundleId: 'com.example.betDrasha.RunnerTests',
  );
}
